// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		'AkarIcons:bell': typeof import('~icons/akar-icons/bell')['default']
		'AkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
		'Bi:arrowLeftRight': typeof import('~icons/bi/arrow-left-right')['default']
		'Bx:fontSize': typeof import('~icons/bx/font-size')['default']
		'Bx:moon': typeof import('~icons/bx/moon')['default']
		'Bx:sun': typeof import('~icons/bx/sun')['default']
		'Cil:language': typeof import('~icons/cil/language')['default']
		ElAside: typeof import('element-plus/es')['ElAside']
		ElButton: typeof import('element-plus/es')['ElButton']
		ElCard: typeof import('element-plus/es')['ElCard']
		ElCol: typeof import('element-plus/es')['ElCol']
		ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
		ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
		ElContainer: typeof import('element-plus/es')['ElContainer']
		ElDropdown: typeof import('element-plus/es')['ElDropdown']
		ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
		ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
		ElFooter: typeof import('element-plus/es')['ElFooter']
		ElHeader: typeof import('element-plus/es')['ElHeader']
		ElInput: typeof import('element-plus/es')['ElInput']
		ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
		ElMain: typeof import('element-plus/es')['ElMain']
		ElMenu: typeof import('element-plus/es')['ElMenu']
		ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
		ElOption: typeof import('element-plus/es')['ElOption']
		ElRow: typeof import('element-plus/es')['ElRow']
		ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
		ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
		ElTable: typeof import('element-plus/es')['ElTable']
		ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
		ElTag: typeof import('element-plus/es')['ElTag']
		'Ep:setting': typeof import('~icons/ep/setting')['default']
		'Fontisto:font': typeof import('~icons/fontisto/font')['default']
		'Gg:menu': typeof import('~icons/gg/menu')['default']
		'HeroiconsOutline:menuAlt1': typeof import('~icons/heroicons-outline/menu-alt1')['default']
		'Icons8:leftArrow': typeof import('~icons/icons8/left-arrow')['default']
		MaterialInput: typeof import('./../components/MaterialInput.vue')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
		Test: typeof import('./../components/test.vue')['default']
	}
}
